version: "2"

services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: movie-booking
#    restart: always
    platform: linux/amd64
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
        - .:/var/www/html
        - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        - ./docker/nginx_log:/var/log/nginx
        - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf
        - ./docker/config/ssl:/ssl/
    links:
        - mysql

  mysql:
    container_name: mb_mysql
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password"
#    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mb_db
      MYSQL_USER: thientri
      MYSQL_PASSWORD: thientri
      MYSQL_ROOT_PASSWORD: root
  node:
      image: node:lts
      volumes:
          - .:/var/www/html
      command: tail -f /dev/null
      working_dir: /var/www/html
      ports:
          - "5173:5173"
      container_name: node
